# Builds the plugins and performs basic smoke tests.
# This is not intended to be a long term solution and is just to hold
# things together during early development.
# It syncs to the most recent IREE nightly release and Jax head.

name: Build Smoketest

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 17 * * *"

concurrency:
  # A PR number if a pull request and otherwise the commit hash. This cancels
  # queued and in-progress runs for the same PR (presubmit) or commit
  # (postsubmit).
  group: ${{ github.event.number || github.sha }}
  cancel-in-progress: true

# Jobs are organized into groups and topologically sorted by dependencies
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checking out repository"
        uses: actions/checkout@e2f20e631ae6d7dd3b768f56a5d2af784dd54791 # v2.5.0

      - name: "Setting up Python"
        uses: actions/setup-python@75f3110429a8c05be0e1bf360334e4cced2b63fa # v2.3.3
        with:
          python-version: "3.10"  # Needs pybind >= 2.10.1 for Python >= 3.11

      - name: Setup Bazelisk
        uses: bazelbuild/setup-bazelisk@v2

      - name: "Sync to latest nightly"
        run: |
          python ./build_tools/sync.py nightly

      - name: "Configure bazel"
        run: |
          CC=clang CXX=clang++ python ./external/iree/configure_bazel.py

      - name: "Build CPU plugin"
        run: |
          bazel build iree/integrations/pjrt/cpu/...
